### ISSUE TITLE
Publication as a CodeClimate officially supported engine

### ISSUE THREAD

**Issue by caiofbpa** [meuspedidos/codeclimate-pylint#1]
This issue will track all the changes needed to this engine in order to be officially supported by CodeClimate and available to everyone.

**Comment by larkinscott** [comment]
Hey @caiofbpa! Thanks again for your work on this! I started testing it locally over the last few weeks. I'm out of the office today, but I'll send you a Slack invite to our community channel on Monday so we can discuss next steps.

**Comment by larkinscott** [comment]
Hey again @caiofbpa! Sent you an invite to our Slack channel. Let me know if you didn't receive it.

**Comment by caiofbpa** [comment]
This process is taking place in the #pylint channel inside CodeClimate's Slack.
